### ISSUE TITLE
Tags/keywords not showing up on extension's page

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt-extensions#10]
![screenshot from 2015-08-21 10-06-28](https://cloud.githubusercontent.com/assets/1427081/9405070/7519fc68-47ec-11e5-8f9f-a9efb0664180.png)

Whereas the [composer.json file has](https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/composer.json#L5-L11):
```json
	"keywords" : [
		"forms",
		"contact",
		"comments",
		"reCaptcha",
		"uploads"
	],
```

**Comment by Mikescops** [comment]
We should tag this with "Mistery".

![image](https://cloud.githubusercontent.com/assets/4266283/9405308/08fcb8f8-47f7-11e5-80f0-16db5e41ae1d.png)

**Comment by jadwigo** [comment]
this seems to be fixed :)
