### ISSUE TITLE
Not able to request a forgotten password

### ISSUE THREAD

**Issue by navelpluisje** [bolt/bolt-extensions#14]
There's no option available to request a new password when you forgot yours.

**Comment by SahAssar** [comment]
It's right there on the login screen:

![untitled](https://cloud.githubusercontent.com/assets/5096632/10180669/87a6ef98-670f-11e5-94e0-7b7b0a37b681.png)

Please reopen the issue If you are not seeing it on your install :)

**Comment by navelpluisje** [comment]
I think you're mixing op an install of bolt and creating an account on extensions.bolt.cm
My problem is on the second one
\

**Comment by SahAssar** [comment]
Sorry, thought I was in bolt/bolt!

My apologies!

**Comment by rarila** [comment]
@SahAssar Hehe, take a break! :sweat_smile::sweat_drops:

**Comment by navelpluisje** [comment]
Can set to closed again. Message in login screen wasn't accurate. Has been fixed now
