### ISSUE TITLE
Weird latest version on a theme

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt-extensions#24]
One theme in the store has a weird "latest version" version.
It's this: http://extensions.bolt.cm/view/a0f0191b-9dcb-11e4-a99b-c5c5895e3a0c

The github repo looks good for me and I have no clue where this version comes from. It's not a branch and not a tag.

![](https://infinit.io/_/kq286e7.png)

**Comment by PhillippOhlandt** [comment]
Ross, would be cool if you look at that in the next time.

**Comment by rossriley** [comment]
I think a pre 1.0 release means that the releases aren't stable and thus the master branch becomes the latest stable release.

I'll have a dig through the composer code to make sure that is the case, but generally a release should be 1.0 or higher.

**Comment by PhillippOhlandt** [comment]
Then my one extension would have the same because its version is `0.1.4`.
http://extensions.bolt.cm/view/452eb1f2-bf69-11e5-bf25-14cdca8e654f

**Comment by rossriley** [comment]
Fixed: http://extensions.bolt.cm/view/a0f0191b-9dcb-11e4-a99b-c5c5895e3a0c

**Comment by PhillippOhlandt** [comment]
Cool, what was the problem?
