### ISSUE TITLE
On `/profile` the names are `<a>` but have no `href`.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt-extensions#35]
See screenshot: 

![screenshot_2016-03-29_20_09_17](https://cloud.githubusercontent.com/assets/1833361/14118579/6647df3c-f5ea-11e5-86c5-384b9019c662.png)

They should have the same link as the 'view' button.

**Comment by GawainLynch** [comment]
Yay! I nagged and nagged when this was in development :smile:

**Comment by SahAssar** [comment]
That isn't the only place either... when viewing a single extension, like /view/d49af7c7-7b34-4396-b436-2f63f4747a7d for example, all the headers under "More Info" are also like this.

**Comment by PhillippOhlandt** [comment]
@SahAssar I guess that's a hack to make them blue :D
